name: Go Test

on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
      - name: Install libs
        run: go mod tidy
      - name: Run go test
        run: go test ./... -v
